#! /usr/bin/env bash

# tmux-cc: Set up iTerm2 tmux integration.
#
# Usage:
#
# ssh target-host -A -t ./bin/tmux-cc
# ... now iTerm2 will attach or reattach to the tmux session.

SSHDIR=$(cd ~ && pwd)/.ssh
AGENT=$SSHDIR/ssh-agent
TMUX_PROG=${TMUX_PROG:-/usr/bin/tmux}

if [ ! -d "$SSHDIR" ]; then
    mkdir -p "$SSHDIR"
    chmod 700 "$SSHDIR"
fi

# Stash the ssh-agent auth socket to that agent forwarding works.
rm -f $AGENT
ln -s $SSH_AUTH_SOCK $AGENT
export SSH_AUTH_SOCK="$AGENT"

if $TMUX_PROG has-session ; then
    exec $TMUX_PROG -u -CC attach
else
    exec $TMUX_PROG -2 -u -CC
fi
