#! /usr/bin/env bash

# Refresh the current branch against the working copy of master.

set -o errexit
set -o nounset
set -o pipefail

readonly GIT=${GIT:-git}
readonly CURRENT=$(${GIT} rev-parse --abbrev-ref HEAD)

## TODO(jpeach): automatically figure out which branch we are
# rebasing onto.
readonly BASE=${BASE:-master}

${GIT} checkout ${BASE}
${GIT} pull
${GIT} checkout ${CURRENT}
${GIT} rebase ${BASE}
