#! /usr/bin/env bash

set -o errexit

readonly TEMPDIR=$(mktemp -d)

install::ubuntu() {
    sudo apt-get install -y git curl
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

. /etc/os-release
case $ID in
ubuntu) install::ubuntu ;;
*) echo "$0: no support for $ID";;
esac


