#! /usr/bin/env bash

set -o errexit

readonly TEMPDIR=$(mktemp -d)

# https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions
install::ubuntu() {
    curl --fail --location -silent https://packages.mozilla.org/apt/repo-signing-key.gpg | \
        sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | \
        sudo tee /etc/apt/sources.list.d/mozilla.list > /dev/null

    echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo tee /etc/apt/preferences.d/mozilla > /dev/null

    sudo apt-get update
    sudo apt-get install firefox
}

. /etc/os-release
case $ID in
ubuntu) install::ubuntu ;;
*) echo "$0: no support for $ID";;
esac


