#! /usr/bin/env bash

set -e # exit on error

WORK=$(mktemp -d)
PREFIX=$HOME/inst/bear

cd $WORK

git clone https://github.com/rizsotto/Bear.git
cd Bear

cmake -DCMAKE_INSTALL_PREFIX=$PREFIX .

make
rm -rf $PREFIX && make install

for prg in $(find $PREFIX/bin -type f) ; do
    ln -sf $prg $HOME/bin/$(basename $prg)
done

cd /
rm -rf $WORK
